# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports =[ 
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = { 
        device = "/dev/mapper/luks-74fe4071-22e0-4d1c-9f6c-2b676dee9283";
        fsType = "ext4";
    };

    boot.initrd.luks.devices."luks-74fe4071-22e0-4d1c-9f6c-2b676dee9283".device = "/dev/disk/by-uuid/74fe4071-22e0-4d1c-9f6c-2b676dee9283";

    fileSystems."/boot" = { 
        device = "/dev/disk/by-uuid/34AD-2497";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
    };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
